### ISSUE TITLE
GFPGAN with the Android

### ISSUE THREAD

**Issue by laverne01** [nuwandda/photo-enhancer#5]
I've been trying to find documentation on building GFPGAN with the Android system but haven't been able to find any. Do you have any advice on this? Thank you.

**Comment by nuwandda** [comment]
I haven't tried it also but I know that there is a version of the upscaler implemented in TFLite. I don't think it is as good as this but maybe you can try it.

**Comment by laverne01** [comment]
Thank you! Do you have any reference links? I would really appreciate it

**Comment by nuwandda** [comment]
Of course. You can try the links below.

- https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/examples/super_resolution/overview.ipynb

- https://github.com/tumuyan/ESRGAN-Android-TFLite-Demo
